// Code generated by MockGen. DO NOT EDIT.
// Source: GoDownload/downloader/url_provider.go

// Package downloader is a generated GoMock package.
package clients

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLProvider is a mock of URLProvider interface.
type MockURLProvider struct {
	ctrl     *gomock.Controller
	recorder *MockURLProviderMockRecorder
}

// MockURLProviderMockRecorder is the mock recorder for MockURLProvider.
type MockURLProviderMockRecorder struct {
	mock *MockURLProvider
}

// NewMockURLProvider creates a new mock instance.
func NewMockURLProvider(ctrl *gomock.Controller) *MockURLProvider {
	mock := &MockURLProvider{ctrl: ctrl}
	mock.recorder = &MockURLProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLProvider) EXPECT() *MockURLProviderMockRecorder {
	return m.recorder
}

// GetURLs mocks base method.
func (m *MockURLProvider) GetURLs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLs indicates an expected call of GetURLs.
func (mr *MockURLProviderMockRecorder) GetURLs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLs", reflect.TypeOf((*MockURLProvider)(nil).GetURLs))
}
